#!/bin/bash
# Launcher script for MEGAsync on Hyprland/Wayland
# Generated by Antigravity for BLACK-ICE ARCH

export XDG_RUNTIME_DIR="/run/user/$(id -u)"
export WAYLAND_DISPLAY="wayland-1"
export QT_QPA_PLATFORM="wayland"
export QT_QPA_PLATFORMTHEME=""
export QT_STYLE_OVERRIDE=""

# Ensure the log directory exists
mkdir -p "$HOME/.cache/mega"
echo "Starting MEGAsync at $(date)" >> "$HOME/.cache/mega/launch.log"

sleep 10 && /usr/bin/megasync >> "$HOME/.cache/mega/launch.log" 2>&1 &
echo "Process ID: $!" >> "$HOME/.cache/mega/launch.log"
