# AstroDark theme for Kitty
# Source: Gogh-Co/Gogh - https://gogh-co.github.io/Gogh/

# Colores especiales
foreground              #9B9FA9
background              #1A1D23
cursor                  #CACCD3
cursor_text_color       #1A1D23
selection_foreground    #1A1D23
selection_background    #ADB0BB
url_color               #50A4E9

# Normal colors (color0 - color7)
color0                  #111317
color1                  #F8747E
color2                  #75AD47
color3                  #D09214
color4                  #50A4E9
color5                  #CC83E3
color6                  #00B298
color7                  #ADB0BB

# Bright colors (color8 - color15)
color8                  #576176
color9                  #FAA5AB
color10                 #A5CD84
color11                 #EFBD58
color12                 #8DC3F1
color13                 #DEAEED
color14                 #27FFDF
color15                 #CACCD3

# Tab bar colors (opcional, combina con el theme)
active_tab_foreground   #1A1D23
active_tab_background   #50A4E9
inactive_tab_foreground #576176
inactive_tab_background #111317
