# Brenda-Everforest — Everforest Dark Hard
foreground              #d3c6aa
background              #1e2326
selection_foreground    #1e2326
selection_background    #a7c080
cursor                  #a7c080
cursor_text_color       #1e2326
url_color               #7fbbb3
active_border_color     #a7c080
inactive_border_color   #4a555b
bell_border_color       #dbbc7f
active_tab_foreground   #1e2326
active_tab_background   #a7c080
inactive_tab_foreground #d3c6aa
inactive_tab_background #272e33
tab_bar_background      #1e2326
color0  #272e33
color8  #4a555b
color1  #e67e80
color9  #e67e80
color2  #a7c080
color10 #a7c080
color3  #dbbc7f
color11 #dbbc7f
color4  #7fbbb3
color12 #7fbbb3
color5  #d699b6
color13 #d699b6
color6  #83c092
color14 #83c092
color7  #d3c6aa
color15 #e6ddc4
