# Isabel-Frappe — Catppuccin Frappé
foreground              #c6d0f5
background              #303446
selection_foreground    #303446
selection_background    #85c1dc
cursor                  #f2d5cf
cursor_text_color       #303446
url_color               #85c1dc
active_border_color     #ca9ee6
inactive_border_color   #626880
bell_border_color       #e5c890
active_tab_foreground   #232634
active_tab_background   #ca9ee6
inactive_tab_foreground #c6d0f5
inactive_tab_background #292c3c
tab_bar_background      #232634
color0  #51576d
color8  #626880
color1  #e78284
color9  #e78284
color2  #a6d189
color10 #a6d189
color3  #e5c890
color11 #e5c890
color4  #8caaee
color12 #8caaee
color5  #ca9ee6
color13 #ca9ee6
color6  #85c1dc
color14 #85c1dc
color7  #b5bfe2
color15 #a5adce
