# Janis-CyberMagenta — Hot magenta/purple cyberpunk
foreground              #ff00ff
background              #0e0018
selection_foreground    #0e0018
selection_background    #ff00ff
cursor                  #ff00ff
cursor_text_color       #0e0018
url_color               #00f3ff
active_border_color     #ff00ff
inactive_border_color   #200030
bell_border_color       #ffff00
active_tab_foreground   #0e0018
active_tab_background   #ff00ff
inactive_tab_foreground #b026ff
inactive_tab_background #150025
tab_bar_background      #0e0018
color0  #200030
color8  #330048
color1  #ff3355
color9  #ff6677
color2  #00ff88
color10 #55ffaa
color3  #ffff00
color11 #ffff66
color4  #6600ff
color12 #9944ff
color5  #ff00ff
color13 #ff66ff
color6  #00f3ff
color14 #66f8ff
color7  #f0d0ff
color15 #ffffff
