#!/bin/bash
# interactive-config.sh - TUI Configuration Generator for BLACK-ICE
# Uses whiptail to generate config/install.conf

SCRIPT_DIR=$(dirname "$(dirname "$(readlink -f "$0")")")
CONFIG_OUT="$SCRIPT_DIR/config/install.conf"

# Check for whiptail
if ! command -v whiptail &>/dev/null; then
    echo "This script requires 'whiptail'. Please install 'libnewt'."
    exit 1
fi

# Colors
export NEWT_COLORS='
root=,black
window=cyan,black
border=blue,black
shadow=black,gray
button=black,green
actbutton=black,cyan
entry=white,black
label=white,black
listbox=white,black
actlistbox=black,cyan
textbox=white,black
acttextbox=black,cyan
helpline=white,black
roottext=white,black
'

whiptail --title "BLACK-ICE ARCH SOTA" --msgbox "Welcome to the SOTA Configuration Wizard.\n\nThis tool will generate the 'install.conf' file for automated deployment." 10 60

# 1. Hostname
HOSTNAME=$(whiptail --title "Hostname" --inputbox "Enter Hostname:" 8 40 "black-ice-node" 3>&1 1>&2 2>&3)

# 2. Encryption
if whiptail --title "Security" --yesno "Enable Full Disk Encryption (LUKS)?" 8 40; then
    ENCRYPT="yes"
    LUKS_PASS=$(whiptail --title "Security" --passwordbox "Enter LUKS Password:" 8 40 3>&1 1>&2 2>&3)
else
    ENCRYPT="no"
    LUKS_PASS=""
fi

# 3. Country
SELECTED_COUNTRY=$(whiptail --title "Mirrors" --menu "Select Country for Mirrors:" 15 40 5 \
"Chile" "South America (Fast)" \
"United States" "Global (Reliable)" \
"Spain" "Europe" \
"Germany" "Europe" \
"Brazil" "South America" 3>&1 1>&2 2>&3)

# 4. Filesystem
FILESYSTEM=$(whiptail --title "Filesystem" --radiolist "Select Root Filesystem:" 10 40 2 \
"ext4" "Stable, Standard" ON \
"btrfs" "Snapshots, Advanced" OFF 3>&1 1>&2 2>&3)

# 5. Kernel
KERNEL=$(whiptail --title "Kernel" --radiolist "Select Kernel:" 10 40 3 \
"linux" "Standard" ON \
"linux-zen" "Desktop Optimized" OFF \
"linux-hardened" "Security Optimized" OFF 3>&1 1>&2 2>&3)

# Generate Config
cat <<EOF > "$CONFIG_OUT"
# BLACK-ICE ARCH CONFIGURATION (Generated by TUI)
HOSTNAME="$HOSTNAME"
ENABLE_LUKS="$ENCRYPT"
LUKS_PASSWORD="$LUKS_PASS"
SELECTED_COUNTRY="$SELECTED_COUNTRY"
FILESYSTEM="$FILESYSTEM"
KERNEL="$KERNEL"

# Fixed Defaults
TIMEZONE="America/Santiago"
KEYBOARD_LAYOUT="la-latin1"
SYSTEM_LANG="es_CL.UTF-8"
EOF

whiptail --title "Success" --msgbox "Configuration saved to:\n$CONFIG_OUT" 8 60
